default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_connections_app_development

test:
  <<: *default
  database: photo_connections_app_test

production:
  <<: *default
  database: photo_connections_app_production
  username: photo_connections_app
  password: <%= ENV['PHOTO_CONNECTIONS_APP_DATABASE_PASSWORD'] %>
